apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app2
  labels:
    app: python-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app2
  template:
    metadata:
      labels:
        app: python-app2
    spec:
      containers:
      - name: python-app2
        image: x.x.x.x:5000/abilash/python-app2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-app2
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: python-app2
  targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: Service
metadata:
  name: python-app2
  labels:
    name: python-app2
spec:
  type: NodePort
  ports:
  - name: https
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: python-app2
