apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app3
  labels:
    app: python-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app3
  template:
    metadata:
      labels:
        app: python-app3
    spec:
      containers:
      - name: python-app3
        image: testpipelineregistry.azurecr.io/abilash/python-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: azr-auth

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-app3
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: python-app3
  targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: Service
metadata:
  name: python-app3
  labels:
    name: python-app3
spec:
  type: NodePort
  ports:
  - name: https
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: python-app3
